-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.department
(
    dept_no character varying(4) COLLATE pg_catalog."default" NOT NULL,
    dept_name character varying(30) COLLATE pg_catalog."default",
    PRIMARY KEY (dept_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character varying(4) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (emp_no, dept_no),
    UNIQUE (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying(4) COLLATE pg_catalog."default" NOT NULL,
    emp_no integer NOT NULL,
    UNIQUE (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.employee
(
    emp_no integer NOT NULL,
    emp_title_id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    first_name character varying(30) COLLATE pg_catalog."default",
    last_name character varying(30) COLLATE pg_catalog."default",
    sex character varying(1) COLLATE pg_catalog."default",
    hire_date date,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.salary
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no, salary),
    UNIQUE (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.title
(
    title_id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    title character varying(30) COLLATE pg_catalog."default",
    PRIMARY KEY (title_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.dept_emp
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (emp_title_id)
    REFERENCES public.title (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salary
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;